# Nome del workflow, visibile nella tab "Actions" di GitHub
name: Build Rclone for Windows

# Specifica quando deve partire il workflow
on:
  # Esegui quando fai un push sul branch 'main'
  push:
    branches: [ "main" ]
  # Permette di avviare il workflow manualmente dalla UI di GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install WinFsp
        run: choco install winfsp -y

      - name: Build rclone.exe
        env:
          CGO_ENABLED: 1
          CGO_CFLAGS: "-IC:/Program Files (x86)/WinFsp/inc/fuse"
          CGO_LDFLAGS: "-LC:/Program Files (x86)/WinFsp/lib"
        run: go build -tags cmount -o rclone.exe -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rclone-windows
          path: rclone.exe
