name: Build rclone Terabox (Windows)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout fork with PR
        uses: actions/checkout@v3
        with:
          repository: x1arch/rclone
          ref: backend/terabox

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install WinFsp
        run: |
          Invoke-WebRequest -Uri https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi -OutFile winfsp.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i', 'winfsp.msi', '/quiet'
        shell: powershell

      - name: Install Mingw-w64 (GCC for Windows)
        run: choco install mingw -y

      - name: Add Mingw to PATH
        run: |
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell

      - name: Set Env Vars for WinFsp headers and libs
        run: |
          echo 'CGO_CFLAGS="-IC:\\Progra~2\\WinFsp\\inc"' >> $env:GITHUB_ENV
          echo 'CGO_LDFLAGS="-LC:\\Progra~2\\WinFsp\\lib -lwinfsp"' >> $env:GITHUB_ENV
        shell: powershell
  
      - name: Build rclone with mount support
        run: go build -tags cmount -o rclone-terabox.exe
  
      - name: Upload rclone.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: rclone-terabox-windows
          path: rclone-terabox.exe

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "TeraBox R-Clone v1-alpha"
          body: "Compiled .exe for rclone with terabox"
          files: rclone-terabox.exe
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
